### ISSUE TITLE
Bug: string.charCodeAt is not a function

### ISSUE THREAD

**Issue by raisty** [polygonplanet/encoding.js#33]
I am getting difficulties while using `const unicodeArray = Encoding.stringToCode(characters);`

My environment:

Node version: v18.8.0
System: macOS Monterey 

Error:

```sh
.../node_modules/encoding-japanese/src/util.js:154
    code[i] = string.charCodeAt(i);
                     ^

TypeError: string.charCodeAt is not a function
```

characters variable is UTF16 (for example):

`肄㮚쨀艒ࠃ隫⢖즯際ᄹ丿௧僚痐ݮᴚﶈ෠뚳Ꝥ%00肸ꬖ겶Œ쉔⑊渾�ʜ꾐齏ⷄ霯ᛙ淨䫼拙䱇脋喳躰썗⭲蕒愝㾻ȉ﷢䴖跔㇆폝⻬ᕴ�퍎⍴偬릎殿婸φ叙疂ȏ덩셯幆下wᾷꭴ尕㢛匈夁ʁ步℘ꑻ޹瘼碞遗潪▅픰ꢘ銪㪺╷襞掣䤬믳贀`

**Comment by polygonplanet** [comment]
@raisty 
[`Encoding.stringToCode`](https://github.com/polygonplanet/encoding.js#code-array-to-string-conversion-codetostringstringtocode) argument can only be passed as a string. Please check if the passed argument `characters` is a string.
If not a string, you will probably get this error because `Encoding.stringToCode` uses `string.charCodeAt` internally.

```javascript
Encoding.stringToCode('abc') // [97, 98, 99]
Encoding.stringToCode('') // []
Encoding.stringToCode('あいう') // [12354, 12356, 12358]

Encoding.stringToCode([97]) // Uncaught TypeError: string.charCodeAt is not a function
```

**Comment by raisty** [comment]
`charCodeAt` is accepting only valid Unicode characters. Then the conclusion is that you cannot pass any character, but only within the Unicode range — more specific — without [surrogate pairs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt#fixing_charcodeat_to_handle_non-basic-multilingual-plane_characters_if_their_presence_earlier_in_the_string_is_known).
